# Generated by Django 2.1 on 2018-11-10 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_time', models.DateTimeField(auto_now_add=True)),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='contacts.Contact')),
            ],
        ),
    ]
