# Generated by Django 2.1 on 2018-11-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sent',
            name='otp',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='sent',
            name='sent_time',
            field=models.DateTimeField(null=True),
        ),
    ]
